{% set version = "3.1.0" %}
{% set name = "sphinx_rtd_theme" %}

package:
  name: {{ name }}-split
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b44276f2c276e909239a4f6c955aa667aaafeb78597923b1c60babc76db78e4c

build:
  number: 0
  skip: True  # [py<38]

outputs:
  - name: {{ name }}
    script: build_base.bat  # [win]
    script: build_base.sh   # [not win]
    requirements:
      host:
        - pip
        - python
        - setuptools
        - wheel
      run:
        - python
        - sphinx >=6,<10
        - docutils >0.18,<0.23
        - sphinxcontrib-jquery >=4,<5
    test:
      source_files:
        - tests
      imports:
        - sphinx_rtd_theme
      requires:
        - pip
        - pytest
      commands:
        - pip check
        - pytest -v tests

  - name: sphinx-rtd-theme
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage(name, min_pin='x.x.x', max_pin='x.x.x') }}
    test:
      imports:
        - sphinx_rtd_theme

about:
  home: https://github.com/readthedocs/sphinx_rtd_theme
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sphinx theme for readthedocs.org
  description: |
    This is a mobile-friendly sphinx theme made for readthedocs.org. It's currently in
    development there and includes some rtd variable checks that can be ignored if you're
    just trying to use it on your project outside of that site.
  dev_url: https://github.com/readthedocs/sphinx_rtd_theme
  doc_url: https://sphinx-rtd-theme.readthedocs.io

extra:
  recipe-maintainers:
    - chohner
    - SylvainCorlay
  skip-lints:
    - missing_pip_check
