{% set version = "0.3.1" %}
{% set sha256 = "6d0481532b5f441b075127a2d755f430f1f8410a50112b1af6b069518548381d" %}
{% set pkg_name = 'sphinx_rtd_theme' %}		

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ pkg_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkg_name[0] }}/{{ pkg_name }}/{{ pkg_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - sphinx_rtd_theme

about:
  home: https://github.com/snide/sphinx_rtd_theme/
  license: MIT
  summary: 'ReadTheDocs.org theme for Sphinx, 2013 version.'

  description: |
    This is a mobile-friendly sphinx theme made for readthedocs.org. It's currently in
    development there and includes some rtd variable checks that can be ignored if you're
    just trying to use it on your project outside of that site.
  dev_url: https://github.com/snide/sphinx_rtd_theme/

extra:
  recipe-maintainers:
    - chohner
    - SylvainCorlay
