travis:
  secure:
    BINSTAR_TOKEN: pp21+kU4/9U5+FS0qbn3WCujT+yWftI53EfcU8w/vg//T4G3elO+PXCskxU+SFg7LVppcU5DrhMTlzRoNFvs8YATFhRPDZ8gASoASLG/h+C2WUUN5lQ2tTYO0o0PRXdEf9WLL69DAoTr8kcfgukHrEkaDrFGvZqXBgIfhev5HKmwdrRbfaiDr4csBh4rnFME3qJ40aBI+10Mqg/JQiEEzE6U8PdbZny2W9+q1Wf4GxNaqSPZwYCgy9a+5G2n+mwowJFcuv/2pMkqLATdsfzx5zis/zgYBtBAa5jnbeeP+EoMP9b3XQYyPFIIeqFpHX8a40rekVsbYBldvKDkFNW2fYdizoADLE7Twid1Hbvp1KCvELHNJzqQYM29IPHVmxsdVY1mUGX2ZalAUNrS3eIGe8dgRlWDfPC3LQypOWBdbu+7mawJ+gh9QPKaCN7rM98ekweI+tcDWkDGwehXdNB/qEoNBhq3s6xgIExW0TlMM4vw14PElEdffT4sNKNZbFDkVmE4n4MOjWo1GsCequpS2kuZ1+YFY67zGryV/ncQxlOWdGNXVWuO03/XO+eEVtVhmomlFT/z3HncxM6gMiAVNYfZxN8s/rPLpb499XBZHA7OQNMWDwluvXR1nFltOxILKghCpfL0O7OWubC84YRcFkziaEzr+ERQTSnaIueZ5kw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
