travis:
  secure:
    BINSTAR_TOKEN: sn/MwjgTNT8ALR4cDqC5Wi4dCpufL0yYjfMu7Vgofg/k3qa+oyaUXvSTfE8iAzZwQQ56EISZXkfBt8I157ab3/6WCgXYdx7ssx36Ke+T7NlwaYTWn8cFR7ZzccHICaVST7PGxd48pNaYN+2CXfo6IAlapb1Zorw45nTfAxlMSLTTma8vKkPTXVjDkKZxqEi+zmlrp2b4DyFFNI/uohZ9zxFfjh5C0rnuiBPllxY48Me+9uvsRZ0VPQT+c9juh0bEUR4hW1DS11HhHp0LDHHTQnoq6ZI2P92UeWGdRZ6vrhFY7qawzfQdSB++PnG6DVafb4K3QeKJ5CWioPYaLMQHYeUQxBUtzTwuWWsCYn5Qsgb/oyiJzEQ3wK6uGIg+JsngsT4oy4/DO7IBCL+tu7sIy4BYgOSOKh+tRAJaV97ieC0heKzib3ysojsZ+Z3zw9B94mScGjO9N4M1ruqUSsea8+2dPGaoaJVCPtnkLeAnm81yinDm0fw5mnfoeZYe1JXO4wuy3fGD7eqilfEQYjnSJK6zRBhF9RvSVr6Pg/S5YmwCl9X5LPXVYGSulEGBYOKRlGUcG3zyBVhrcE066DxgxslHB6F5OV869lPnXIW5G/toLyWCVTILxMgKQ7UC1TjHAp/XTTKy+22DVTFG8/pZNQSer0BBdap/NsCwyMLm55U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
